name: CI - Map Integration Feature

on:
  push:
    branches: [ "feat/map-integration" ]
  pull_request:
    branches: [ "feat/map-integration" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test
      
    - name: Build Project
      run: npm run build
